/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ProjectDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-04-07T21:28:19.344429018Z[GMT]")

public class ProjectDTO {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("scheduledEffort")
  private Integer scheduledEffort = null;

  @SerializedName("personIds")
  private List<Integer> personIds = null;

  public ProjectDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProjectDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ProjectDTO scheduledEffort(Integer scheduledEffort) {
    this.scheduledEffort = scheduledEffort;
    return this;
  }

   /**
   * Get scheduledEffort
   * @return scheduledEffort
  **/
  @Schema(description = "")
  public Integer getScheduledEffort() {
    return scheduledEffort;
  }

  public void setScheduledEffort(Integer scheduledEffort) {
    this.scheduledEffort = scheduledEffort;
  }

  public ProjectDTO personIds(List<Integer> personIds) {
    this.personIds = personIds;
    return this;
  }

  public ProjectDTO addPersonIdsItem(Integer personIdsItem) {
    if (this.personIds == null) {
      this.personIds = new ArrayList<Integer>();
    }
    this.personIds.add(personIdsItem);
    return this;
  }

   /**
   * Get personIds
   * @return personIds
  **/
  @Schema(description = "")
  public List<Integer> getPersonIds() {
    return personIds;
  }

  public void setPersonIds(List<Integer> personIds) {
    this.personIds = personIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectDTO projectDTO = (ProjectDTO) o;
    return Objects.equals(this.name, projectDTO.name) &&
        Objects.equals(this.description, projectDTO.description) &&
        Objects.equals(this.scheduledEffort, projectDTO.scheduledEffort) &&
        Objects.equals(this.personIds, projectDTO.personIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, scheduledEffort, personIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectDTO {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    scheduledEffort: ").append(toIndentedString(scheduledEffort)).append("\n");
    sb.append("    personIds: ").append(toIndentedString(personIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
