/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AssignedPersonDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ProjectDetailDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-04-07T21:28:19.344429018Z[GMT]")

public class ProjectDetailDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("scheduledEffort")
  private Integer scheduledEffort = null;

  @SerializedName("assignedPersons")
  private List<AssignedPersonDTO> assignedPersons = null;

  public ProjectDetailDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ProjectDetailDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProjectDetailDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ProjectDetailDTO scheduledEffort(Integer scheduledEffort) {
    this.scheduledEffort = scheduledEffort;
    return this;
  }

   /**
   * Get scheduledEffort
   * @return scheduledEffort
  **/
  @Schema(description = "")
  public Integer getScheduledEffort() {
    return scheduledEffort;
  }

  public void setScheduledEffort(Integer scheduledEffort) {
    this.scheduledEffort = scheduledEffort;
  }

  public ProjectDetailDTO assignedPersons(List<AssignedPersonDTO> assignedPersons) {
    this.assignedPersons = assignedPersons;
    return this;
  }

  public ProjectDetailDTO addAssignedPersonsItem(AssignedPersonDTO assignedPersonsItem) {
    if (this.assignedPersons == null) {
      this.assignedPersons = new ArrayList<AssignedPersonDTO>();
    }
    this.assignedPersons.add(assignedPersonsItem);
    return this;
  }

   /**
   * Get assignedPersons
   * @return assignedPersons
  **/
  @Schema(description = "")
  public List<AssignedPersonDTO> getAssignedPersons() {
    return assignedPersons;
  }

  public void setAssignedPersons(List<AssignedPersonDTO> assignedPersons) {
    this.assignedPersons = assignedPersons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectDetailDTO projectDetailDTO = (ProjectDetailDTO) o;
    return Objects.equals(this.id, projectDetailDTO.id) &&
        Objects.equals(this.name, projectDetailDTO.name) &&
        Objects.equals(this.description, projectDetailDTO.description) &&
        Objects.equals(this.scheduledEffort, projectDetailDTO.scheduledEffort) &&
        Objects.equals(this.assignedPersons, projectDetailDTO.assignedPersons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, scheduledEffort, assignedPersons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectDetailDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    scheduledEffort: ").append(toIndentedString(scheduledEffort)).append("\n");
    sb.append("    assignedPersons: ").append(toIndentedString(assignedPersons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
