/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * TimeSlotDetailDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-31T00:35:36.207118415Z[GMT]")

public class TimeSlotDetailDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("date")
  private LocalDate date = null;

  @SerializedName("startTime")
  private org.joda.time.* startTime = null;

  @SerializedName("endTime")
  private org.joda.time.* endTime = null;

  @SerializedName("personId")
  private Integer personId = null;

  public TimeSlotDetailDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TimeSlotDetailDTO date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @Schema(description = "")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

  public TimeSlotDetailDTO startTime(org.joda.time.* startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @Schema(description = "")
  public org.joda.time.* getStartTime() {
    return startTime;
  }

  public void setStartTime(org.joda.time.* startTime) {
    this.startTime = startTime;
  }

  public TimeSlotDetailDTO endTime(org.joda.time.* endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @Schema(description = "")
  public org.joda.time.* getEndTime() {
    return endTime;
  }

  public void setEndTime(org.joda.time.* endTime) {
    this.endTime = endTime;
  }

  public TimeSlotDetailDTO personId(Integer personId) {
    this.personId = personId;
    return this;
  }

   /**
   * Get personId
   * @return personId
  **/
  @Schema(description = "")
  public Integer getPersonId() {
    return personId;
  }

  public void setPersonId(Integer personId) {
    this.personId = personId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeSlotDetailDTO timeSlotDetailDTO = (TimeSlotDetailDTO) o;
    return Objects.equals(this.id, timeSlotDetailDTO.id) &&
        Objects.equals(this.date, timeSlotDetailDTO.date) &&
        Objects.equals(this.startTime, timeSlotDetailDTO.startTime) &&
        Objects.equals(this.endTime, timeSlotDetailDTO.endTime) &&
        Objects.equals(this.personId, timeSlotDetailDTO.personId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, date, startTime, endTime, personId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeSlotDetailDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    personId: ").append(toIndentedString(personId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
