/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.PersonDTO;
import io.swagger.client.model.PersonDetailDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PersonJsonControllerApi
 */
@Ignore
public class PersonJsonControllerApiTest {

    private final PersonJsonControllerApi api = new PersonJsonControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createPersonJSONTest() throws Exception {
        PersonDTO body = null;
        PersonDetailDTO response = api.createPersonJSON(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deletePersonJSONTest() throws Exception {
        Integer id = null;
        api.deletePersonJSON(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getPersonDetailJSONTest() throws Exception {
        Integer id = null;
        PersonDetailDTO response = api.getPersonDetailJSON(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updatePersonJSONTest() throws Exception {
        PersonDTO body = null;
        Integer id = null;
        PersonDetailDTO response = api.updatePersonJSON(body, id);

        // TODO: test validations
    }
}
