/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.TimeSlotDTO;
import io.swagger.client.model.TimeSlotDetailDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TimeSlotJsonControllerApi
 */
@Ignore
public class TimeSlotJsonControllerApiTest {

    private final TimeSlotJsonControllerApi api = new TimeSlotJsonControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTimeSlotJSONTest() throws Exception {
        TimeSlotDTO body = null;
        TimeSlotDetailDTO response = api.createTimeSlotJSON(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTimeSlotJSONTest() throws Exception {
        Integer id = null;
        api.deleteTimeSlotJSON(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTimeSlotDetailJSONTest() throws Exception {
        Integer id = null;
        TimeSlotDetailDTO response = api.getTimeSlotDetailJSON(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateTimeSlotJSONTest() throws Exception {
        TimeSlotDTO body = null;
        Integer id = null;
        TimeSlotDetailDTO response = api.updateTimeSlotJSON(body, id);

        // TODO: test validations
    }
}
